name = "grudge-tracker"
main = "dist/worker/index.js"
compatibility_date = "2024-05-17"

# D1 database binding
[[d1_databases]]
binding = "DB"
# database_id to be filled by user
database_name = "grudges"

[site]
bucket = "dist/site"
entry-point = "."
binding = "ASSETS"
